spring.application.name=backend

# ==========================================
# POSTGRESQL
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/bd_copa2026
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SERVER
# ==========================================

server.port=8080